[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/yuin/gopher-lua"

[[constraint]]
  branch = "master"
  name = "github.com/cjoudrey/gluahttp"

[[constraint]]
  branch = "master"
  name = "layeh.com/gopher-json"
